### ISSUE TITLE
Headless DE-STRESS fix: .env-headless file

### ISSUE THREAD

**Issue by LunaPrau** [wells-wood-research/de-stress#145]
.env-headless file needs HEADLESS_DESTRESS_BATCH_SIZE defined. E.g.:

POSTGRES_PASSWORD=testpassword

GUNICORN_WORKERS=2
APP_PORT=8181

EVOEF2_BINARY_PATH=/dependencies_for_de-stress/EvoEF2/EvoEF2
DFIRE2_FOLDER_PATH=/dependencies_for_de-stress/DFIRE2-pair/
ROSETTA_BINARY_PATH=/dependencies_for_de-stress/rosetta_src_2020.08.61146_bundle/main/source/bin/score_jd2.linuxgccrelease
AGGRESCAN3D_SCRIPT_PATH=/dependencies_for_de-stress/Aggrescan3D/aggrescan3D_cli_run.py

RQ_DASHBOARD_REDIS_URL=redis://redis:6379
RQ_DASHBOARD_PORT=8182

MAX_RUN_TIME=200
HEADLESS_DESTRESS_WORKERS=3
HEADLESS_DESTRESS_BATCH_SIZE=10

**Comment by LunaPrau** [comment]
PR #148

**Comment by MichaelJamesStam** [comment]
Resolved
