### ISSUE TITLE
Headless DE-STRESS fix: README commands

### ISSUE THREAD

**Issue by LunaPrau** [wells-wood-research/de-stress#146]
In summary:
- docker compose instead of docker-compose
- docker container created by docker compose is named "de-stress-big-structure" not "de-stress_big-structure"
- wrong .env file given in the last docker run command

Leading to fixed commands:
1. docker compose -f headless-compose.yml build
2. docker run -it --rm -v /absolute/path/to/de-stress/dependencies_for_de-stress/ de-stress-big-structure:latest sh build_dependencies.sh
3. docker run -it --rm --env-file .env-headless -v //absolute/path/to/de-stress/dependencies_for_de-stress/:/dependencies_for_de-stress -v /absolute/path/to/input_path/:/input_path de-stress-big-structure:latest poetry run headless_destress /input_path

**Comment by LunaPrau** [comment]
PR #147

**Comment by MichaelJamesStam** [comment]
Resolved

**Comment by MichaelJamesStam** [comment]
Resolved
